import Head from "next/head";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className='bg-slate-900'>
      <Head>
        <title>Joaquin | Front-End Developer</title>
        <meta name='description' content='Generated bycreate next  app' />
        <link rel='icon' href='./favicon.png' />
      </Head>
      <Hero />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
